# Generated by Django 2.1.3 on 2018-12-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_oscars_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='oscars_photo',
        ),
    ]
