# Generated by Django 2.1.3 on 2018-11-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_app', models.CharField(max_length=200)),
                ('app_id', models.IntegerField(default=0)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('date_finished', models.CharField(max_length=10)),
                ('desc_achieved_1', models.CharField(blank=True, max_length=200)),
                ('desc_achieved_2', models.CharField(blank=True, max_length=200)),
                ('desc_achieved_3', models.CharField(blank=True, max_length=200)),
                ('desc_achieved_4', models.CharField(blank=True, max_length=200)),
                ('desc_achieved_5', models.CharField(blank=True, max_length=200)),
                ('desc_technical_1', models.CharField(blank=True, max_length=200)),
                ('desc_technical_2', models.CharField(blank=True, max_length=200)),
                ('desc_technical_3', models.CharField(blank=True, max_length=200)),
                ('desc_technical_4', models.CharField(blank=True, max_length=200)),
                ('desc_technical_5', models.CharField(blank=True, max_length=200)),
                ('tags_1', models.CharField(blank=True, max_length=20)),
                ('tags_2', models.CharField(blank=True, max_length=20)),
                ('tags_3', models.CharField(blank=True, max_length=20)),
                ('tags_4', models.CharField(blank=True, max_length=20)),
                ('tags_5', models.CharField(blank=True, max_length=20)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
    ]
