# Generated by Django 2.1.3 on 2018-11-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='photo_main',
            new_name='photo_main_portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo_main_project',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
