# Generated by Django 2.1.3 on 2018-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181125_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link_to_project',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags_6',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
