# Generated by Django 2.1.3 on 2018-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20181126_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link_to_project',
            field=models.CharField(blank=True, default=0, max_length=300),
        ),
    ]
