# Generated by Django 2.1.3 on 2018-11-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20181126_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link_to_project',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
