# Generated by Django 2.1.3 on 2018-12-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20181126_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='desc_technical_0',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
