# Generated by Django 2.1.3 on 2019-09-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_portfolio_photo_main_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link_to_demo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link_to_product_page',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
