# Generated by Django 2.2.5 on 2019-09-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190904_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='desc_technical_0',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='desc_technical_1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='desc_technical_2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='desc_technical_3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='desc_technical_4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='desc_technical_5',
        ),
    ]
